# Generated by Django 5.1.15 on 2026-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                ("timeframe", models.CharField(max_length=8)),
                ("timestamp", models.DateTimeField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timeframe", "timestamp"],
                        name="marketdata__symbol_938cbe_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "timeframe", "timestamp"),
                        name="uniq_candle_per_symbol_timeframe_ts",
                    )
                ],
            },
        ),
    ]
