# Generated by Django 5.1.15 on 2026-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="kind",
            field=models.CharField(
                choices=[("sma_crossover", "SMA Crossover"), ("rsi", "RSI")],
                default="sma_crossover",
                max_length=32,
            ),
        ),
    ]
