# Generated by Django 5.1.15 on 2026-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0002_strategy_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="commission_pct",
            field=models.FloatField(
                default=0.0004,
                help_text="Taker fee per side, fraction (0.0004 = 0.04%)",
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="funding_interval_hours",
            field=models.FloatField(
                default=8.0, help_text="Hours between funding charges"
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="funding_rate",
            field=models.FloatField(
                default=0.0,
                help_text="Funding per interval, fraction (longs pay if > 0)",
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="slippage_bps",
            field=models.FloatField(
                default=1.0, help_text="Adverse fill per side, basis points"
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="spread_bps",
            field=models.FloatField(
                default=1.0, help_text="Half-spread crossed per side, basis points"
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="trade",
            name="funding",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="trade",
            name="gross_pnl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
    ]
