# Generated by Django 5.1.15 on 2026-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0003_backtest_commission_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="equity_curve",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
