# Generated by Django 5.1.15 on 2026-06-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0004_backtest_equity_curve"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="total_commission",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="total_funding",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="warnings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
