# Generated by Django 5.1.15 on 2026-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backtester",
            "0005_backtest_total_commission_backtest_total_funding_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="kind",
            field=models.CharField(
                choices=[
                    ("sma_crossover", "SMA Crossover"),
                    ("rsi", "RSI"),
                    ("graph", "Graph"),
                ],
                default="sma_crossover",
                max_length=32,
            ),
        ),
    ]
